# Generated by Django 3.2.4 on 2021-06-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_formatter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
